### ISSUE TITLE
Important PFX key file missing

### ISSUE THREAD

**Issue by SFM61319** [clemenskoprolin/light-party#1]
**Describe the bug**
Hi! I'm that [u/SFM61319](https://reddit.com/user/SFM61319) on Reddit.  
I've forked this repo earlier and cloned it. Then when I tried to build the project, it threw an error which said *Unable to get MD5 checksum for key file `LightParty_TemporaryKey.pfx`, file `\light-party\LightParty\LightParty_TemporaryKey.pfx` does not exist*. Please check if you have missed that file, because nothing can be done/built because of this error.  
  
**To Reproduce**
1. Clone the repo onto a different environment  
2. Build the solution

**Expected behavior**
Build should be successful, but throws an error

**Screenshots**
*I unforked and deleted the repo to update it freshly to the error-less in the future, so I don't have a screenshot at the moment*

**Information:**
- Windows Version: 2004
- System type: 64-bit operating system, x64-based processor
- Light Party Version: most likely 1.0.0 (unknown because build was unsuccessful)

**Additional context**
Please update the repo with the file inside the LightParty directory. (I am on mobile so ignore any mistakes).  
  
Thank you!

**Comment by clemenskoprolin** [comment]
That's the key file for signing the project and uploading it to the Microsoft Store. It probably wouldn't be a good idea to publish it here, so I'll update the project on GitHub so that you won't need it. Shouldn't take long.
Thanks for the report!

**Comment by clemenskoprolin** [comment]
With the commit 0cc00fe , the problem doesn't occur anymore on my computer. Can you confirm that,  @SFM61319 ?

**Comment by SFM61319** [comment]
Please hold on a second, I am cloning it again

**Comment by SFM61319** [comment]
@clemenskoprolin it works! There are few bugs(?) but it works now

**Comment by clemenskoprolin** [comment]
OK, if there are any serious bugs, please open another bug report. I'll close this issue for now.
Thank you again for the report! 👍

**Comment by SFM61319** [comment]
Hey I have a doubt. Why did you create [2 different ColorPicker color inputs](https://github.com/clemenskoprolin/light-party/blob/0cc00fe71c7ded4999e76e5771b436505267745d/LightParty/Pages/LightControl/RGBColorPicker.xaml#L18) when you couldve done the same but better with just 1 ColorPicker?

**Comment by clemenskoprolin** [comment]
I find even the smallest size of the color wheel too big, therefore I put it into a viewbox which makes it smaller. But this made the hex color input field smaller, too. Therefore I created a second color picker in which only the hex color input field is visible.
They synchronize each other so that the user doesn't see two different values.

**Comment by SFM61319** [comment]
@clemenskoprolin?

**Comment by clemenskoprolin** [comment]
Yes?

**Comment by SFM61319** [comment]
oh no nothing. the site is working weirdly today and did not show me your reply, so i mentioned you

**Comment by clemenskoprolin** [comment]
Are you still working on your suggestions, @SFM61319 ? If not, I would also happily implement them!

**Comment by SFM61319** [comment]
@clemenskoprolin yes I am working on those rn. I did not know what version of `AcrylicBrush` and `NavigationView` (you have used the default `Windows.UI.Xaml.Controls`), so I changed them to `Microsoft.UI.Xaml.Controls` and `Microsoft.UI.Xaml.Media` (both WinUI 2.4.3). But one problem with that is the `NavigationPane` doesn't support acrylic any longer in WinUI2. So I have tried to find a work around but failed, so I left it as is.  
  
Meanwhile, can you please work on a bug that won't let the users to move around in the app unless you pair a light bulb device with the app? I wanted to test all the backgrounds of the frame pages by moving around in the app and see if they worked, but I didn't connect a bulb (which I don't have in the first place), so the app won't stop searching for any bulbs near by and also won't let me navigate to different pages, not even the settings page. It would be really helpul if you solved it. Or I can just send you a PR and you can accept it, then sync your local version with the updated fluent code, and then you can rebuild the app and if you have a Phillips bulb at your home, you can try navigating to different pages to see if the acrylic is working fine (it should, but testing is important so). Or I can open another issue if you want me to.  
(That didn't come off rude, did it?)

**Comment by clemenskoprolin** [comment]
Oh no! I read your comment too late, sorry. With the commit e1c894b , I already implemented a custom acrylic app bar and a navigation view that uses the design. But you wanted to do even more, didn't you? You can still implement that!
It is intentional that the user cannot navigate to other pages when the app hasn't registered itself. It would crash because the other pages expect a connected Bridge. But there is a solution for you: By pressing 5 times the F2 key anywhere in the app, you can activate demo mode, where you don't need any real Bridge. Try it out!
