### ISSUE TITLE
Bridge registration not working for some users.

### ISSUE THREAD

**Issue by clemenskoprolin** [clemenskoprolin/light-party#2]
**Describe the bug**
Multiple users have problems to register this application to their Bridge. They are stuck on the "Register Application" Page.

**To Reproduce**
Introduction -> Legal information -> Location of Bridge ("Searching for your Philips Hue Bridge ...") -> Registration of the application ("Register Application")

**Expected behavior**
The application should register itself and navigate to BridgeConfig where they should see information about the Bridge like the name, version etc.

**Screenshots**
![4R73BGH](https://user-images.githubusercontent.com/47183762/92948840-534cd680-f45a-11ea-84a3-edec16864808.png)
(Thanks a lot to [garywoo on Reddit](https://www.reddit.com/user/garywoo/) for this screenshot!)

**Information:**
- Windows Version: 2004
- System type: 64-bit operating system, x64-based processor
- Light Party Version: 1.1.0

**Additional context**
Personally, I don’t have this issue. Therefore, I have to guess what exactly the reason for this bug is and it could take a few updates and commits before it is completely fixed.
With the commits 6e5e43f25067691131b19d5b8b4b319a6ced0d05 and e1c894b518c8163e00f01071acf5706ade510cf0 I already tried to fix it, but users are still reporting the bug.

**Comment by clemenskoprolin** [comment]
With the commits 0cba38d14c6896f5c38701d70d1fe8f68d2c7b0c and 460e6c200f388edd120f4556c4a79ca6b101b09a I tried again to fix this issue. Light Party version 1.1.1 will contain these fixes, but like mantiond above: I can't validade that these commits fix this issue.

**Comment by clemenskoprolin** [comment]
Thanks to the reddit user [Xornop_](https://www.reddit.com/user/Xornop_/) and the new log file with the commit b5c037121ef0c6a409412dee97fe1883a8f239bc there is now a error log!

`Error on registration process - Message: An error occurred while sending the request. - InnerException: System.Exception: De tekst die bij deze foutcode hoort, kan niet worden gevonden.
Kan geen verbinding met de server maken.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__15.MoveNext() + 0x79d`

Translations: 
`De tekst die bij deze foutcode hoort, kan niet worden gevonden` - The text belonging to this error can not be found.
`Kan geen verbinding met de server maken.` - Unable to connect to the server.

**Comment by Garywoo** [comment]
I updated to 1.1.1. Launched the app, and it was on the same screen as in the screenshot. Pressing the button on my bridge didn’t do anything in the app. The issue continues.

**Comment by clemenskoprolin** [comment]
Thanks for the info! You could help me by sending your log, too.
Please uninstall your current version of Light Party and [install this version](https://drive.google.com/file/d/1cJP1SyQ05llk1tniZhwhsna_hofh0asE/view?usp=sharing) ([Here](https://clemenskoprolin.com/lightparty/docs/howtodownload/) is the documentation for the manual installation). Once you start the application, you should see a message like "DebugLog is activated. Path to file: ". Now go on with the normal setup until the bug occurs. Then close Light Party and copy the file whose path you saw in beforehand.
The easiest way to send me the log is probably my mail (contact@clemenskoprolin.com).

**Comment by clemenskoprolin** [comment]
It seems like the commit e6d58da4bc5b970f94070370d3da367b23a9bb99 fixed the bug. It was caused by missing capabilities in the Package.appxmanifest. The fix is part of the update 1.1.2. However, I'll wait until the update rolls out and I get final feedback if the issue is really solved.

**Comment by clemenskoprolin** [comment]
Since I'm not getting any more reports of this bug, I'll close this issue for the time being. Thank you for all who helped fixing it!
