### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by stuaxo** [clemenskoprolin/light-party#5]
Hi,
   I'd like to try this in Linux.  Not expecting direct support first (though I guess I could try building and running under dotnet on linux?), but if you released this on github releases, I could try and run this under Wine or Mono.

Cheers
S

**Comment by clemenskoprolin** [comment]
Hey, thanks for the request.
As this application is based on UWP there is unfortunately currently no native way to build it for Linux. [Some had luck with Wine](https://askubuntu.com/questions/991858/is-it-possible-to-run-windows-10-uwp-apps-on-ubuntu), but I don't know if it will work with this app. But I do upload the .msixbundle packages with the .msix files in it to [GitHub releases](https://github.com/clemenskoprolin/light-party/releases), so you could at least try it.
Keep me up to date, thanks again

**Comment by stuaxo** [comment]
Maybe UNO is an option ?

**Comment by clemenskoprolin** [comment]
At least not for now, it would require a lot of effort to port the UWP application to UNO. Had you any luck with Wine?

**Comment by stuaxo** [comment]
That's fair enough - I will get round to trying this, but need some free time as it's a little involved.

In the meantime, I found an app on Android that does a similar thing, and a gnome shell extension that turns the lights on and off from the UI.

I'll close this so it's not cluttering your issues :)
